apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
  selector:
    matchLabels:
      app: {{ .Release.Name }}